import type { TagDef } from "@mm/shared-types";

/**
 * Canonical taxonomy. Each entry has a stable kebab-case id used everywhere
 * else in the system. Labels are human-facing; categories drive color/grouping
 * in the UI. Keep ids lowercased — `mapTag` matches case-insensitively.
 */
export const TAGS: TagDef[] = [
  // ── Genres ────────────────────────────────────────────────────────────────
  { id: "rock", label: "Rock", category: "genre" },
  { id: "pop", label: "Pop", category: "genre" },
  { id: "metal", label: "Metal", category: "genre" },
  { id: "punk", label: "Punk", category: "genre" },
  { id: "hip-hop", label: "Hip-Hop", category: "genre" },
  { id: "rnb", label: "R&B", category: "genre" },
  { id: "soul", label: "Soul", category: "genre" },
  { id: "funk", label: "Funk", category: "genre" },
  { id: "blues", label: "Blues", category: "genre" },
  { id: "jazz", label: "Jazz", category: "genre" },
  { id: "country", label: "Country", category: "genre" },
  { id: "folk", label: "Folk", category: "genre" },
  { id: "electronic", label: "Electronic", category: "genre" },
  { id: "classical", label: "Classical", category: "genre" },
  { id: "reggae", label: "Reggae", category: "genre" },
  { id: "world", label: "World", category: "genre" },
  { id: "soundtrack", label: "Soundtrack", category: "genre" },
  { id: "comedy", label: "Comedy", category: "genre" },

  // ── Subgenres ─────────────────────────────────────────────────────────────
  { id: "alt-rock", label: "Alt Rock", category: "subgenre" },
  { id: "indie-rock", label: "Indie Rock", category: "subgenre" },
  { id: "hard-rock", label: "Hard Rock", category: "subgenre" },
  { id: "classic-rock", label: "Classic Rock", category: "subgenre" },
  { id: "prog-rock", label: "Prog Rock", category: "subgenre" },
  { id: "psychedelic-rock", label: "Psychedelic Rock", category: "subgenre" },
  { id: "garage-rock", label: "Garage Rock", category: "subgenre" },
  { id: "post-rock", label: "Post-Rock", category: "subgenre" },
  { id: "post-punk", label: "Post-Punk", category: "subgenre" },
  { id: "pop-punk", label: "Pop Punk", category: "subgenre" },
  { id: "hardcore", label: "Hardcore", category: "subgenre" },
  { id: "ska", label: "Ska", category: "subgenre" },
  { id: "swing", label: "Swing", category: "subgenre" },
  { id: "grunge", label: "Grunge", category: "subgenre" },
  { id: "nu-metal", label: "Nu Metal", category: "subgenre" },
  { id: "thrash-metal", label: "Thrash Metal", category: "subgenre" },
  { id: "death-metal", label: "Death Metal", category: "subgenre" },
  { id: "black-metal", label: "Black Metal", category: "subgenre" },
  { id: "doom-metal", label: "Doom Metal", category: "subgenre" },
  { id: "metalcore", label: "Metalcore", category: "subgenre" },
  { id: "alt-metal", label: "Alt Metal", category: "subgenre" },
  { id: "industrial", label: "Industrial", category: "subgenre" },
  { id: "new-wave", label: "New Wave", category: "subgenre" },
  { id: "blues-rock", label: "Blues Rock", category: "subgenre" },
  { id: "soft-rock", label: "Soft Rock", category: "subgenre" },
  { id: "post-grunge", label: "Post-Grunge", category: "subgenre" },
  { id: "rap-rock", label: "Rap Rock", category: "subgenre" },
  { id: "gangsta-rap", label: "Gangsta Rap", category: "subgenre" },
  { id: "conscious-hip-hop", label: "Conscious Hip-Hop", category: "subgenre" },
  { id: "trip-hop", label: "Trip-Hop", category: "subgenre" },
  { id: "house", label: "House", category: "subgenre" },
  { id: "techno", label: "Techno", category: "subgenre" },
  { id: "drum-and-bass", label: "Drum & Bass", category: "subgenre" },
  { id: "ambient", label: "Ambient", category: "subgenre" },
  { id: "edm", label: "EDM", category: "subgenre" },
  { id: "bluegrass", label: "Bluegrass", category: "subgenre" },
  { id: "americana", label: "Americana", category: "subgenre" },
  { id: "singer-songwriter", label: "Singer-Songwriter", category: "subgenre" },
  { id: "alt-country", label: "Alt Country", category: "subgenre" },
  { id: "outlaw-country", label: "Outlaw Country", category: "subgenre" },
  { id: "smooth-jazz", label: "Smooth Jazz", category: "subgenre" },
  { id: "fusion", label: "Fusion", category: "subgenre" },

  // ── Moods ─────────────────────────────────────────────────────────────────
  { id: "mellow", label: "Mellow", category: "mood" },
  { id: "energetic", label: "Energetic", category: "mood" },
  { id: "melancholic", label: "Melancholic", category: "mood" },
  { id: "uplifting", label: "Uplifting", category: "mood" },
  { id: "aggressive", label: "Aggressive", category: "mood" },
  { id: "romantic", label: "Romantic", category: "mood" },
  { id: "dark", label: "Dark", category: "mood" },
  { id: "atmospheric", label: "Atmospheric", category: "mood" },
  { id: "groovy", label: "Groovy", category: "mood" },
  { id: "chill", label: "Chill", category: "mood" },

  // ── Eras (decade buckets) ─────────────────────────────────────────────────
  { id: "pre-50s", label: "Pre-1950s", category: "era" },
  { id: "50s", label: "1950s", category: "era" },
  { id: "60s", label: "1960s", category: "era" },
  { id: "70s", label: "1970s", category: "era" },
  { id: "80s", label: "1980s", category: "era" },
  { id: "90s", label: "1990s", category: "era" },
  { id: "2000s", label: "2000s", category: "era" },
  { id: "2010s", label: "2010s", category: "era" },
  { id: "2020s", label: "2020s", category: "era" },

  // ── Regions ───────────────────────────────────────────────────────────────
  { id: "us", label: "United States", category: "region" },
  { id: "uk", label: "United Kingdom", category: "region" },
  { id: "canada", label: "Canada", category: "region" },
  { id: "australia", label: "Australia", category: "region" },
  { id: "ireland", label: "Ireland", category: "region" },
  { id: "germany", label: "Germany", category: "region" },
  { id: "france", label: "France", category: "region" },
  { id: "japan", label: "Japan", category: "region" },
  { id: "latin-america", label: "Latin America", category: "region" },
  { id: "africa", label: "Africa", category: "region" },
];

export const TAG_BY_ID: Record<string, TagDef> = Object.fromEntries(
  TAGS.map((t) => [t.id, t]),
);

/**
 * Lowercased raw-string → canonical tag id.
 * Keys are matched against the lowercased, whitespace-trimmed raw value.
 * `normalize.ts` also slug-matches as a secondary path.
 */
export const SYNONYMS: Record<string, string> = {
  // Rock family
  "rock": "rock",
  "rock & roll": "rock",
  "rock and roll": "rock",
  "alternative": "alt-rock",
  "alternative rock": "alt-rock",
  "alt rock": "alt-rock",
  "alt-rock": "alt-rock",
  "indie": "indie-rock",
  "indie rock": "indie-rock",
  "hard rock": "hard-rock",
  "classic rock": "classic-rock",
  "progressive rock": "prog-rock",
  "prog rock": "prog-rock",
  "psychedelic rock": "psychedelic-rock",
  "psychedelic": "psychedelic-rock",
  "garage rock": "garage-rock",
  "post-rock": "post-rock",
  "post rock": "post-rock",
  "grunge": "grunge",
  "southern rock": "classic-rock",

  // Punk
  "punk": "punk",
  "punk rock": "punk",
  "post-punk": "post-punk",
  "post punk": "post-punk",
  "pop punk": "pop-punk",
  "pop-punk": "pop-punk",
  "hardcore": "hardcore",
  "hardcore punk": "hardcore",
  "ska": "ska",
  "ska punk": "ska",
  "swing": "swing",
  "swing revival": "swing",

  // Metal
  "metal": "metal",
  "heavy metal": "metal",
  "nu metal": "nu-metal",
  "nu-metal": "nu-metal",
  "thrash": "thrash-metal",
  "thrash metal": "thrash-metal",
  "death metal": "death-metal",
  "black metal": "black-metal",
  "doom metal": "doom-metal",
  "metalcore": "metalcore",
  "industrial": "industrial",
  "industrial metal": "industrial",
  "rap rock": "rap-rock",
  "rap metal": "rap-rock",
  "rapcore": "rap-rock",
  "alternative metal": "alt-metal",
  "alt metal": "alt-metal",
  "industrial rock": "industrial",
  "new wave": "new-wave",
  "blues rock": "blues-rock",
  "soft rock": "soft-rock",
  "post grunge": "post-grunge",
  "post-grunge": "post-grunge",

  // Pop
  "pop": "pop",
  "pop rock": "pop",
  "synth-pop": "pop",
  "synthpop": "pop",
  "dance-pop": "pop",

  // Hip-Hop / R&B
  "hip hop": "hip-hop",
  "hip-hop": "hip-hop",
  "rap": "hip-hop",
  "gangsta rap": "gangsta-rap",
  "west coast rap": "gangsta-rap",
  "east coast rap": "hip-hop",
  "conscious hip hop": "conscious-hip-hop",
  "conscious hip-hop": "conscious-hip-hop",
  "trip hop": "trip-hop",
  "trip-hop": "trip-hop",
  "r&b": "rnb",
  "rnb": "rnb",
  "rhythm and blues": "rnb",
  "soul": "soul",
  "neo soul": "soul",
  "funk": "funk",

  // Electronic
  "electronic": "electronic",
  "electronica": "electronic",
  "house": "house",
  "techno": "techno",
  "drum and bass": "drum-and-bass",
  "drum & bass": "drum-and-bass",
  "dnb": "drum-and-bass",
  "ambient": "ambient",
  "edm": "edm",
  "dance": "edm",

  // Blues / Jazz / Country / Folk
  "blues": "blues",
  "electric blues": "blues",
  "chicago blues": "blues",
  "delta blues": "blues",
  "jazz": "jazz",
  "smooth jazz": "smooth-jazz",
  "jazz fusion": "fusion",
  "fusion": "fusion",
  "country": "country",
  "country rock": "country",
  "alt country": "alt-country",
  "alt-country": "alt-country",
  "outlaw country": "outlaw-country",
  "bluegrass": "bluegrass",
  "americana": "americana",
  "folk": "folk",
  "folk rock": "folk",
  "singer-songwriter": "singer-songwriter",
  "singer songwriter": "singer-songwriter",

  // Other
  "classical": "classical",
  "orchestral": "classical",
  "reggae": "reggae",
  "world": "world",
  "world music": "world",
  "soundtrack": "soundtrack",
  "score": "soundtrack",
  "film score": "soundtrack",
  "comedy": "comedy",
  "stand-up comedy": "comedy",
  "stand up comedy": "comedy",

  // Region demonyms (sometimes appear in the embedded genre stream)
  "american": "us",
  "british": "uk",
  "english": "uk",
  "scottish": "uk",
  "welsh": "uk",
  "irish": "ireland",
  "canadian": "canada",
  "australian": "australia",
  "german": "germany",
  "french": "france",
  "japanese": "japan",

  // Moods
  "mellow": "mellow",
  "calm": "mellow",
  "energetic": "energetic",
  "upbeat": "energetic",
  "melancholic": "melancholic",
  "melancholy": "melancholic",
  "sad": "melancholic",
  "somber": "melancholic",
  "uplifting": "uplifting",
  "happy": "uplifting",
  "aggressive": "aggressive",
  "angry": "aggressive",
  "intense": "aggressive",
  "romantic": "romantic",
  "love": "romantic",
  "dark": "dark",
  "atmospheric": "atmospheric",
  "ethereal": "atmospheric",
  "groovy": "groovy",
  "chill": "chill",
  "relaxed": "chill",
  "laid back": "chill",
};
