import type { ArtistsDoc, Graph } from "@mm/shared-types";

export const mockGraph: Graph = {
  generatedAt: "2026-05-19T00:00:00.000Z",
  nodes: [
    {
      id: "blues",
      label: "Blues",
      category: "genre",
      artistCount: 4,
      playCount: 6880,
      weight: 9,
    },
    {
      id: "classic-rock",
      label: "Classic Rock",
      category: "subgenre",
      artistCount: 4,
      playCount: 7280,
      weight: 9,
    },
    {
      id: "heavy-metal",
      label: "Heavy Metal",
      category: "subgenre",
      artistCount: 2,
      playCount: 4950,
      weight: 7,
    },
    {
      id: "thrash-metal",
      label: "Thrash Metal",
      category: "subgenre",
      artistCount: 2,
      playCount: 4950,
      weight: 7,
    },
    {
      id: "alt-metal",
      label: "Alt Metal",
      category: "subgenre",
      artistCount: 2,
      playCount: 3700,
      weight: 6,
    },
    {
      id: "progressive-rock",
      label: "Progressive Rock",
      category: "subgenre",
      artistCount: 3,
      playCount: 6000,
      weight: 8,
    },
    {
      id: "alt-rock",
      label: "Alt Rock",
      category: "genre",
      artistCount: 3,
      playCount: 3900,
      weight: 6,
    },
    {
      id: "grunge",
      label: "Grunge",
      category: "subgenre",
      artistCount: 1,
      playCount: 1400,
      weight: 4,
    },
    {
      id: "psychedelic-rock",
      label: "Psychedelic Rock",
      category: "subgenre",
      artistCount: 2,
      playCount: 3700,
      weight: 6,
    },
    {
      id: "country",
      label: "Country",
      category: "genre",
      artistCount: 1,
      playCount: 1200,
      weight: 4,
    },
  ],
  edges: [
    { source: "blues", target: "classic-rock", weight: 3 },
    { source: "heavy-metal", target: "thrash-metal", weight: 2 },
    { source: "alt-metal", target: "progressive-rock", weight: 1 },
    { source: "alt-metal", target: "alt-rock", weight: 1 },
    { source: "classic-rock", target: "progressive-rock", weight: 1 },
    { source: "alt-rock", target: "grunge", weight: 1 },
    { source: "classic-rock", target: "psychedelic-rock", weight: 2 },
    { source: "progressive-rock", target: "psychedelic-rock", weight: 1 },
    { source: "country", target: "blues", weight: 1 },
  ],
  stats: {
    artistCount: 14,
    taggedArtistCount: 14,
    rawTagCount: 36,
  },
};

export const mockArtists: ArtistsDoc = {
  generatedAt: "2026-05-19T00:00:00.000Z",
  artists: [
    {
      id: "a1",
      name: "Eric Clapton",
      slug: "eric-clapton",
      playCount: 2200,
      starred: true,
      tags: ["blues", "classic-rock"],
      rawTags: { embedded: ["blues rock", "classic rock"] },
      topAlbums: [
        {
          id: "al1",
          name: "Slowhand",
          year: 1977,
          playCount: 540,
          genres: ["Blues", "Classic Rock"],
        },
      ],
      yearMin: 1970,
      yearMax: 2018,
    },
    {
      id: "a2",
      name: "Pantera",
      slug: "pantera",
      playCount: 1850,
      starred: true,
      tags: ["heavy-metal", "thrash-metal"],
      rawTags: { embedded: ["groove metal", "thrash metal"] },
      topAlbums: [
        {
          id: "al2",
          name: "Vulgar Display of Power",
          year: 1992,
          playCount: 620,
          genres: ["Heavy Metal", "Thrash Metal"],
        },
      ],
      yearMin: 1988,
      yearMax: 2000,
    },
    {
      id: "a3",
      name: "Metallica",
      slug: "metallica",
      playCount: 3100,
      starred: true,
      tags: ["heavy-metal", "thrash-metal"],
      rawTags: { embedded: ["heavy metal", "thrash"] },
      topAlbums: [
        {
          id: "al3",
          name: "Master of Puppets",
          year: 1986,
          playCount: 980,
          genres: ["Heavy Metal", "Thrash Metal"],
        },
      ],
      yearMin: 1983,
      yearMax: 2023,
    },
    {
      id: "a4",
      name: "Deftones",
      slug: "deftones",
      playCount: 1600,
      starred: true,
      tags: ["alt-metal", "alt-rock"],
      rawTags: { embedded: ["alternative metal", "alternative rock"] },
      topAlbums: [
        {
          id: "al4",
          name: "White Pony",
          year: 2000,
          playCount: 510,
          genres: ["Alt Metal", "Alt Rock"],
        },
      ],
      yearMin: 1995,
      yearMax: 2020,
    },
    {
      id: "a5",
      name: "Tool",
      slug: "tool",
      playCount: 2100,
      starred: true,
      tags: ["alt-metal", "progressive-rock"],
      rawTags: { embedded: ["progressive metal", "alternative metal"] },
      topAlbums: [
        {
          id: "al5",
          name: "Lateralus",
          year: 2001,
          playCount: 660,
          genres: ["Alt Metal", "Progressive Rock"],
        },
      ],
      yearMin: 1992,
      yearMax: 2022,
    },
    {
      id: "a6",
      name: "B.B. King",
      slug: "bb-king",
      playCount: 1300,
      starred: false,
      tags: ["blues"],
      rawTags: { embedded: ["electric blues"] },
      topAlbums: [
        {
          id: "al6",
          name: "Live at the Regal",
          year: 1965,
          playCount: 420,
          genres: ["Blues"],
        },
      ],
      yearMin: 1957,
      yearMax: 2008,
    },
    {
      id: "a7",
      name: "George Thorogood",
      slug: "george-thorogood",
      playCount: 980,
      starred: false,
      tags: ["blues", "classic-rock"],
      rawTags: { embedded: ["blues rock", "boogie rock"] },
      topAlbums: [
        {
          id: "al7",
          name: "Move It on Over",
          year: 1978,
          playCount: 320,
          genres: ["Blues", "Classic Rock"],
        },
      ],
      yearMin: 1977,
      yearMax: 2011,
    },
    {
      id: "a8",
      name: "Rush",
      slug: "rush",
      playCount: 1700,
      starred: true,
      tags: ["classic-rock", "progressive-rock"],
      rawTags: { embedded: ["progressive rock", "hard rock"] },
      topAlbums: [
        {
          id: "al8",
          name: "Moving Pictures",
          year: 1981,
          playCount: 540,
          genres: ["Classic Rock", "Progressive Rock"],
        },
      ],
      yearMin: 1974,
      yearMax: 2012,
    },
    {
      id: "a9",
      name: "Live",
      slug: "live",
      playCount: 900,
      starred: false,
      tags: ["alt-rock"],
      rawTags: { embedded: ["alternative rock", "post-grunge"] },
      topAlbums: [
        {
          id: "al9",
          name: "Throwing Copper",
          year: 1994,
          playCount: 300,
          genres: ["Alt Rock"],
        },
      ],
      yearMin: 1991,
      yearMax: 2006,
    },
    {
      id: "a10",
      name: "Jimi Hendrix",
      slug: "jimi-hendrix",
      playCount: 2400,
      starred: true,
      tags: ["blues", "classic-rock"],
      rawTags: { embedded: ["psychedelic rock", "blues rock"] },
      topAlbums: [
        {
          id: "al10",
          name: "Are You Experienced",
          year: 1967,
          playCount: 760,
          genres: ["Classic Rock", "Blues"],
        },
      ],
      yearMin: 1967,
      yearMax: 1970,
    },
    {
      id: "a11",
      name: "Nirvana",
      slug: "nirvana",
      playCount: 1400,
      starred: true,
      tags: ["alt-rock", "grunge"],
      rawTags: { embedded: ["grunge", "alternative rock"] },
      topAlbums: [
        {
          id: "al11",
          name: "Nevermind",
          year: 1991,
          playCount: 510,
          genres: ["Grunge", "Alt Rock"],
        },
      ],
      yearMin: 1989,
      yearMax: 1994,
    },
    {
      id: "a12",
      name: "The Beatles",
      slug: "the-beatles",
      playCount: 2600,
      starred: true,
      tags: ["classic-rock", "psychedelic-rock"],
      rawTags: { embedded: ["classic rock", "psychedelic rock"] },
      topAlbums: [
        {
          id: "al12",
          name: "Abbey Road",
          year: 1969,
          playCount: 800,
          genres: ["Classic Rock", "Psychedelic Rock"],
        },
      ],
      yearMin: 1963,
      yearMax: 1970,
    },
    {
      id: "a13",
      name: "Pink Floyd",
      slug: "pink-floyd",
      playCount: 2200,
      starred: true,
      tags: ["progressive-rock", "psychedelic-rock"],
      rawTags: { embedded: ["progressive rock", "psychedelic rock"] },
      topAlbums: [
        {
          id: "al13",
          name: "The Dark Side of the Moon",
          year: 1973,
          playCount: 730,
          genres: ["Progressive Rock", "Psychedelic Rock"],
        },
      ],
      yearMin: 1967,
      yearMax: 2014,
    },
    {
      id: "a14",
      name: "Johnny Cash",
      slug: "johnny-cash",
      playCount: 1200,
      starred: false,
      tags: ["country", "blues"],
      rawTags: { embedded: ["country", "americana"] },
      topAlbums: [
        {
          id: "al14",
          name: "At Folsom Prison",
          year: 1968,
          playCount: 420,
          genres: ["Country", "Blues"],
        },
      ],
      yearMin: 1957,
      yearMax: 2002,
    },
  ],
  byTag: {
    blues: ["a1", "a6", "a7", "a10", "a14"],
    "classic-rock": ["a1", "a7", "a8", "a10", "a12"],
    "heavy-metal": ["a2", "a3"],
    "thrash-metal": ["a2", "a3"],
    "alt-metal": ["a4", "a5"],
    "progressive-rock": ["a5", "a8", "a13"],
    "alt-rock": ["a4", "a9", "a11"],
    grunge: ["a11"],
    "psychedelic-rock": ["a12", "a13"],
    country: ["a14"],
  },
};
