name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type-check
        run: yarn typecheck

      - name: Tests
        run: yarn test

      - name: Prettier
        run: yarn format:check
